version: '2'

volumes:

  seedpagarme-mysql-data:
    driver: local

  seedpagarme-redis-data:

  seedpagarme-mysql-data:
    driver: local


    driver: local

services:
  mysql:
    image: mysql:5.7

    container_name: seedpagarme-mysql
    volumes:
      - seedpagarme-mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=seedpagarme
      - MYSQL_DATABASE=seedpagarme
      - MYSQL_USER=seedpagarme
      - MYSQL_PASSWORD=seedpagarme

  cache:
    image: redis:4.0
    container_name: seedpagarme-redis
    command: --appendonly yes
    volumes:
      - seedpagarme-redis-data:/data
    ports:
      - "6380:6379"

  app:
    image: ambientum/php:7.3-nginx

    container_name: seedpagarme-app

    volumes:
      - .:/var/www/app
    ports:
      - "8081:8080"
    links:
    - mysql
    - cache


  